/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SocialLinks = IDL.Record({
  'twitch' : IDL.Opt(IDL.Text),
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'steam' : IDL.Opt(IDL.Text),
  'discord' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
});
export const Trophies = IDL.Record({
  'bronze' : IDL.Nat,
  'gold' : IDL.Nat,
  'silver' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfileStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PlayerProfile = IDL.Record({
  'bio' : IDL.Text,
  'status' : ProfileStatus,
  'country' : IDL.Text,
  'owner' : IDL.Principal,
  'socialLinks' : SocialLinks,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'highlightVideoUrl' : IDL.Opt(IDL.Text),
  'trophies' : Trophies,
  'avatar' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminUpdateProfile' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        SocialLinks,
        IDL.Vec(IDL.Text),
        Trophies,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'approveProfile' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, SocialLinks],
      [],
      [],
    ),
  'getApprovedProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [PlayerProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectProfile' : IDL.Func([IDL.Principal], [], []),
  'setAvatar' : IDL.Func([ExternalBlob], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, SocialLinks],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SocialLinks = IDL.Record({
    'twitch' : IDL.Opt(IDL.Text),
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'steam' : IDL.Opt(IDL.Text),
    'discord' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
  });
  const Trophies = IDL.Record({
    'bronze' : IDL.Nat,
    'gold' : IDL.Nat,
    'silver' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfileStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PlayerProfile = IDL.Record({
    'bio' : IDL.Text,
    'status' : ProfileStatus,
    'country' : IDL.Text,
    'owner' : IDL.Principal,
    'socialLinks' : SocialLinks,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'highlightVideoUrl' : IDL.Opt(IDL.Text),
    'trophies' : Trophies,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminUpdateProfile' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          SocialLinks,
          IDL.Vec(IDL.Text),
          Trophies,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'approveProfile' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, SocialLinks],
        [],
        [],
      ),
    'getApprovedProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [PlayerProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectProfile' : IDL.Func([IDL.Principal], [], []),
    'setAvatar' : IDL.Func([ExternalBlob], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, SocialLinks],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };