/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PlayerProfile {
  'bio' : string,
  'status' : ProfileStatus,
  'country' : string,
  'owner' : Principal,
  'socialLinks' : SocialLinks,
  'name' : string,
  'tags' : Array<string>,
  'highlightVideoUrl' : [] | [string],
  'trophies' : Trophies,
  'avatar' : [] | [ExternalBlob],
}
export type ProfileStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SocialLinks {
  'twitch' : [] | [string],
  'twitter' : [] | [string],
  'instagram' : [] | [string],
  'steam' : [] | [string],
  'discord' : [] | [string],
  'youtube' : [] | [string],
}
export interface Trophies {
  'bronze' : bigint,
  'gold' : bigint,
  'silver' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminUpdateProfile' : ActorMethod<
    [
      Principal,
      string,
      string,
      string,
      SocialLinks,
      Array<string>,
      Trophies,
      [] | [string],
    ],
    undefined
  >,
  'approveProfile' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<
    [string, string, string, SocialLinks],
    undefined
  >,
  'getApprovedProfiles' : ActorMethod<[], Array<PlayerProfile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingProfiles' : ActorMethod<[], Array<PlayerProfile>>,
  'getProfile' : ActorMethod<[Principal], PlayerProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectProfile' : ActorMethod<[Principal], undefined>,
  'setAvatar' : ActorMethod<[ExternalBlob], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, string, SocialLinks],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];